---
title: "Хершел-Максвелл и нормальное распределение"
author: "Винни-Пух"
date: "`r Sys.Date()`"
lang: ru-RU
otherlangs: en-GB
fontsize: 11pt
biblio-style: alphabetic
mainfont: "Linux Libertine O"
sansfont: "Linux Libertine O"
monofont: "Linux Libertine O"
link-citations: yes
description: "Вывод нормальной функции плотности из предпосылок"
output: 
  pdf_document:
    fig_caption: yes
    highlight: tango
    keep_tex: yes
    latex_engine: xelatex
    citation_package: biblatex
    number_sections: no
    toc: yes
header-includes: 
  - \newfontfamily{\cyrillicfonttt}{Linux Libertine O}
  - \newfontfamily{\cyrillicfont}{Linux Libertine O}
  - \newfontfamily{\cyrillicfontsf}{Linux Libertine O}
  - \newcommand{\E}{\mathbb{E}}
  - \newcommand{\Var}{\mathbb{V}ar}
  - \renewcommand{\P}{\mathbb{P}}
---

## Молекулы газа

В замкнутом загончике на плоскости хаотично движутся молекулы газа. Мы ловим одну из них случайно и измеряем вектор скоростей
\[
V = \begin{pmatrix}
V_x \\
V_y \\
\end{pmatrix}.
\]

Максвелл предположил, что 

М1. Если мы повернём нашу картинку на произвольный угол и повторим измерения, то закон распределения нового вектора $V'$ будет совпадать с законом распределения вектора $V$.

М2. Если мы знаем горизонтальную составляющую скорости, то это не даёт нам никакой информации о вертикальной составляющей, то есть случайные величины $V_x$ и $V_y$ независимы.

Заметим, что единицы измерения скорости мы можем выбираться произвольно, поэтому давайте дополним предположения Максвелла предположением

М3. Единицы измерения скорости выбраны так, что $\Var(V_x)=1$.


## Первый поворот

Помимо горизонтальной и вертикальной составлящих вектора скорости, $V_x$ и $V_y$, рассмотрим ещё две величины, $U$ — угол с горизонтальной осью и $R=\sqrt{V_x^2+V_y^2}$ — скалярную скорость, длину вектора скорости.

Естественно, $V_x = R\cos U$, $V_y = R\sin U$.

* Какой вектор получится, если вектор $V$ повернуть на $90^{\circ}$ против часовой стрелки?

Получится вектор
\[
V'=\begin{pmatrix}
-V_y \\
V_x \\
\end{pmatrix}
\]

По предпосылке М1 вектор $V'$ должен иметь такое же распределение, как вектор $V$.

* Чему равны $\E(V_x)$, $\E(V_y)$, $\Var(V_y)$?

Раз уж $V' \sim V$, то $-V_y \sim V_x$ и $V_x \sim V_y$. Значит $\E(-V_y) = \E(V_x)$, и одновременно $\E(V_x) = \E(V_y)$. Это возможно только в случае $\E(V_x) = \E(V_y) = 0$.

Строго говоря, осталась ещё возможность, что математическое ожидание не существует.

Аналогично, $\Var(V_x) = \Var(V_y)$ и по предпосылке М3 $\Var(V_x) = \Var(V_y) = 1$.

* Как распределена величина $U$? 

Заметим, что при повороте на произвольный угол $\alpha$, этот угол прибавляется к величине $U$. Если при этом сумма выйдет за $2\pi$, то нужно ещё и вычесть $2\pi$. По предпосылке М1 функция плотности $U$ может быть только постоянной, $f(u+\alpha)=f(u)$ при $0\leq u +\alpha < 2\pi$.

Значит $U$ распределена равномерно на $[0;2\pi)$ и её функция плотности равна
\[
f(u) = \begin{cases}
\frac{1}{2\pi}, \text{ если } u \in [0;2\pi) \\
0, \text{ иначе} \\
\end{cases}
\]

## Вид функции плотности $f(v_x, v_y)$

* Какой вид имеет совместная функция плотности $f(v_x, v_y)$?

По предпосылке М1 совместная функция плотности может зависить только от длины вектора скорости $R$, но не от угла $U$. Для удобства запишем её как функцию квадрата $R$:

\[
f(v_x, v_y) = h(v_x^2 + v_y^2)
\]

По предпосылке М2 компоненты $V_x$ и $V_y$ независимы, поэтому совместная функция плотности должна раскладываться в произведение частных плотностей. Для удобства выразим их также через квадраты составляющих скорости:

\[
f(v_x, v_y) = f(v_x) \cdot f(v_y) = g(v_x^2) \cdot g(v_y^2)
\]

В итоге мы получили забавное соотношение
\[
h(v_x^2 + v_y^2) = g(v_x^2) \cdot g(v_y^2)
\]

Функция от суммы равна произведению функций:
\[
h(a + b) = g(a)g(b)
\]


## Дифференциальное уравнение

* Как связаны $h(a)$ и $h'(a)$?

Возьмём $b=0$, получим, что $h(a)=g(a)g(0)$.

Возьмём производную по $b$:
\[
h'(a+b)=g(a)g'(b)
\]

Подставим $b=0$, получим
\[
h'(a)=g(a)g'(0)
\]


Итого, получаем, что 
\[
\frac{h'(a)}{h(a)} = \frac{g'(0)}{g(0)}
\]

Другими словами производная $h'(a)$ равна исходной функции $h(a)$, умноженной на константу $k=\frac{g'(0)}{g(0)}$:

\[
h'(a) = h(a) \cdot k
\]

Этому условию удовлетворяет только функция $h(a) = e^{ka}$ и пропорциональные ей функции, то есть

\[
h(a) = c \cdot e^{ka}
\]

Таким образом мы нашли вид совместной функции плотности величин $V_x$ и $V_y$:

\[
f(v_x, v_y) = h(v_x^2 + v_y^2) = c \cdot e^{k(v_x^2 + v_y^2)} 
\]

Величины $V_x$ и $V_y$ одинаково распределены, независимы, поэтому частная функция плотности $V_x$ имеет вид
\[
f(v_x) = \sqrt{c} \cdot e^{kv_x^2}
\]

Осталось лишь найти константы $c$ и $k$!

## В поисках $k$

Прежде всего заметим, что $k<0$. Если бы константа $k$ была бы больше нуля, то тогда с ростом $x$ экспонента $e^{kv_x^2}$ уходила бы на бесконечность, и площадь под функцией плотности $f(v_x)$ не равнялась бы единице.

Мы уже знаем, что $\E(V_x)=0$, а единицы измерения скорости выбраны так, что $\Var(V_x)=1$. Замечаем, что в нашем случае $\Var(V_x)=\E(V_x^2)$. Осталось решить уравнение $\E(V_x^2)=1$ и найти $k$.

Переходим к интегралам! Мы будем брать его по частям!

\begin{multline}
\E(V_x^2)=\int_{-\infty}^{+\infty} v_x^2 f(v_x) \, dv_x = 
  \int_{-\infty}^{+\infty} v_x \cdot v_x \cdot \sqrt{c} \cdot e^{kv_x^2} \, dv_x =\\
=\left. v_x \cdot \sqrt{c} \cdot e^{kv_x^2} \cdot (k/2) \right\rvert_{v_x = -\infty}^{v_x=+\infty} - \int_{-\infty}^{+\infty} 1 \cdot \sqrt{c} \cdot e^{kv_x^2} \cdot (1/2k) \, dv_x
\end{multline}

Замечаем, что уменьшаемое равно нулю:
\[
\left. v_x \cdot \sqrt{c} \cdot e^{kv_x^2} \cdot (k/2) \right\rvert_{v_x = -\infty}^{v_x=+\infty} = 0.
\]

А вычитаемое можно записать через исходную функцию плотности:

\[
\int_{-\infty}^{+\infty} 1 \cdot \sqrt{c} \cdot e^{kv_x^2} \cdot (1/2k) \, dv_x = \frac{1}{2k} \int_{-\infty}^{+\infty}f(v_x) \, dx = \frac{1}{2k} \cdot 1
\]

Следовательно,
\[
\E(V_x^2)= -\frac{1}{2k} = 1
\]

Отсюда $k=-\frac{1}{2}$.

## В поисках $c$

Теперь мы знаем, что совместная функция плотности величин $V_x$ и $V_y$ имеет вид
\[
f(v_x, v_y) = h(v_x^2 + v_y^2) = c \cdot e^{-\frac{1}{2}(v_x^2 + v_y^2)} 
\]

* Какой вид имеет совместная функция плотности величин $R$ и $U$?

Удобнее работать не с плотностями, а с дифференциальными формами
\[
\P(V_x \in [v_x;v_x + dv_x], V_y \in [v_y;v_y + dv_y]) \sim f(v_x, v_y) dv_x \wedge dv_y
\]

Подставим $v_x = r\cos u$ и $v_y = r\sin u$. После упрощения получим, что $dv_x \wedge dv_y = r \cdot dr \wedge du$.

\[
\P(R \in [r;r+dr], U\in [u;u+du]) \sim f(r\cos u, r\sin u) r \cdot dr \wedge du = c \cdot r \cdot e^{-r^2/2} \cdot dr \wedge du
\]

Следовательно, совместная функция плотности величин $R$ и $U$ имеет вид
\[
f(r, u) = 
\begin{cases}
c \cdot r \cdot e^{-r^2/2}, \text{ при } r>0, u \in [0;2\pi) \\
0, \text{ иначе} \\
\end{cases}
\]

Заметим, что функция совместная функция плотности раскладывается в произведение $f(r, u) = f(r) \cdot f(u)$, поскольку величины $R$ и $U$ независимы. Вопрос лишь в том, как поделить константу $c$ в этом разложении $f(r, u)$ на сомножетели $f(r)$ и $f(u)$.

Интеграл $\int r e^{-r^2/2} dr$ легко берётся:
\[
\int_{-\infty}^{+\infty} r e^{-r^2/2} dr = 1
\]

Следовательно, $f(r) = r e^{-r^2/2}$ и $f(u) = c$. 

Мы уже знаем, что величина $U$ равномерна на $[0;2\pi]$, следовательно, $c=1/2\pi$.


## Нормальная стандартная величина

Мы пришли к выводу, что функция плотности величины $V_x$ имеет вид
\[
f(v_x) = \frac{1}{\sqrt{2\pi}} e^{-\frac{1}{2}v_x^2}
\]

При этом $\E(V_x)=0$ и $\Var(V_x)=1$.

Величина с такой функцией плотности называется стандартной нормальной случайной величиной и обозначается $N(0;1)$.

## Другие единицы измерения скорости

Рассмотрим линейной преобразование величины $V_x$, $W = \mu + \sigma V_x$. Можно найти ожидаемое значение и дисперсию $W$, $\E(W) = \mu$, $\Var(W) = \sigma^2$.

Найдём функцию плотности $W$. Естественнее работать не с плотностью, а с дифференциальной формой: достаточно подставить в неё выражение для $v_x$, $v_x = \frac{w-\mu}{\sigma}$.

\begin{multline}
\P(V_x \in [v_x;v_x + dv_x]) \sim f(v_x) dv_x = f\left(\frac{w-\mu}{\sigma}\right) d\frac{w-\mu}{\sigma} = \frac{1}{\sigma} f\left(\frac{w-\mu}{\sigma}\right) dw = \\
= \frac{1}{\sqrt{2\pi} \sigma} e^{-\frac{(w-\mu)^2}{2\sigma^2}} \sim \P(W \in [w;w + dw])
\end{multline}

Отсюда функция плотности величины $W$ равна
\[
f(w) =  \frac{1}{\sqrt{2\pi} \sigma} e^{-\frac{(w-\mu)^2}{2\sigma^2}}
\]

Величина с такой функцией плотностью называется нормальной случайной величиной с математическим ожиданием $\mu$ и дисперсией $\sigma^2$ и обозначается $N(\mu; \sigma^2)$.

