---
title: "Эпсилон-архив"
output: html_document
lang: russian
---

* [github-репозиторий журнала Эпсилон](https://github.com/bdemeshev/epsilon/)


### Эпсилон-2, Ведутся строительные работы

* [Эпсилон-2 бета версия](https://github.com/bdemeshev/epsilon/raw/master/e_002/e_002.pdf)

* Борис Демешев, [Частная корреляция](https://github.com/bdemeshev/epsilon/raw/master/e_002/correlation/correlation.pdf)
* Борис Демешев, [Доказательство от принцессы](https://github.com/bdemeshev/epsilon/raw/master/e_002/princess/princess.pdf)
* Артём Филатов, [Задачи по линейной алгебре из ШАДа](https://github.com/bdemeshev/epsilon/raw/master/e_002/linal_shad/linal_shad.pdf)
* Кирилл Фурманов, [Важность коэффициентов](https://github.com/bdemeshev/epsilon/raw/master/e_002/reg_importance/reg_importance.pdf)



### Эпсилон-1, май 2015

* [Эпсилон-1 единым файлом](https://github.com/bdemeshev/epsilon/raw/master/e_001/e_001.pdf)


* [Вступительное слово](https://github.com/bdemeshev/epsilon/raw/master/e_001/foreword/foreword.pdf)


* Кирилл Фурманов, [Как выбрать функциональную форму уравнения регрессии?](https://github.com/bdemeshev/epsilon/raw/master/e_001/functional-form/functional-form.pdf) Диагностика остатков на графике и с помощью тестов.

* Кирилл Фурманов, Борис Демешев, [Эконометрика: типичные ошибки студентов и аспирантов](https://github.com/bdemeshev/epsilon/raw/master/e_001/metrics-errors/metrics-errors.pdf). Мы знаем, как разозлить и умилостивить комиссию на защите ВКР!

* Саша Кузнецова, [Метод $k$-средних и распознавание рукописных цифр](https://github.com/bdemeshev/epsilon/raw/master/e_001/knn/knn.pdf). Один из базовых методов кластеризации с кодом R.

* Андрей Зубанов, [Кто выигрывает рэп-баттлы?](https://github.com/bdemeshev/epsilon/raw/master/e_001/battle/battle.pdf). Статистика даст ответ!

* [Весёлый уголок](https://github.com/bdemeshev/epsilon/raw/master/e_001/fun/fun.pdf). Гальтон и новости ПДД.

* Андрей Костырка, [Новости CrossValidated: выпуск 1](https://github.com/bdemeshev/epsilon/raw/master/e_001/qa/qa.pdf). Отличный обзор новостей со [stats.stackexchange.com](http://stats.stackexchange.com/)

* Настя Игнатьева, [QR-код или немного дополненной реальности](https://github.com/bdemeshev/epsilon/raw/master/e_001/qr-code/ar1.pdf). Хочешь научиться расшифровывать QR-код невооруженным глазом?

* Иван Станкевич, [Сгладить, нельзя не сгладить! Пара слов о методах сезонной корректировки](https://github.com/bdemeshev/epsilon/raw/master/e_001/season/season.pdf). Волшебные заклинания X11, X12, X13 для сглаживания сезонности. 

* [Бобры](https://github.com/bdemeshev/epsilon/raw/master/e_001/bobr/bobr.pdf). Бобры умеют сглаживать сезонность!

* [Задачи](https://github.com/bdemeshev/epsilon/raw/master/e_001/problems/problems.pdf). Пять задач по разным темам: от эконометрики до теории игр.

* [Стол заказов](https://github.com/bdemeshev/epsilon/raw/master/e_001/stol_zakazov/stol_zakazov.pdf). Нам нужны новые статьи! Хотите написать?
