---
title: "Очевидные равенства"
author: "Винни-Пух"
date: "5/5/2017"
output: pdf_document
lang: ru-RU
---


Есть много комбинаторных равенств, в которых мелькают $C_n^k$. Некоторые из них становятся очевидными при правильном прочтении.

Поехали!

* Число подмножеств размера $n$ в множестве из $N$ элементов:
\[
C_N^n = C_N^{N-n}
\]
    - Слева: количество способов покрасить $n$ шаров в белый цвет из $N$ чёрных.
    - Справа: количество способов покрасить $N-n$ шаров в чёрный цвет из $N$ белых.

* Число различных подмножеств в множестве из $n$ элементов:
\[
\sum_{k=0}^n C_n^k = 2^n
\]

    - Слева: количество подмножеств размера 0 плюс количество подмножеств размера 1 плюс \ldots
    - Справа: включать ли первый элемент умножить на включать ли второй элемент умножить на \ldots

* Количество подмножеств размера $n+1$ в множестве из $N+1$ элемента с выделенным «лидером»:
\[
nC_N^n = NC_{N-1}^{n-1}
\]
    - Слева: сначала выбрали подмножество размера $n$ из множества в $N$ элемент. Затем из этих $n$ элементов выбрали лидера.
    - Справа: сначала выбрали из $N$ элементов лидера. Затем из оставшихся $N-1$ элементов выбрали $n-1$ нелидеров.

* Количество подмножеств в множестве из $N$ элементов с «лидером»:
\[
N \cdot 2^{N-1} = 1\cdot C_N^1 + 2 \cdot C_N^2 + \ldots+ N\cdot C_N^N
\]
    - Слева: сначала из $N$ элементов выбираем лидера. Затем из оставшихся $N-1$ элемента выбираем произвольное подмножество нелидеров.
    - Справа: количество подмножеств из одного элемента помножить на один способ выбрать внутри лидера плюс количество подмножеств из двух элементов помножить на два способа выбрать внутри лидера плюс \ldots

* Число подмножеств размера $n$ в множестве из $N$ элементов:
\[
C_N^n = C_{N-1}^n + C_{N-1}^{n-1}
\]
    - Слева: количество подмножеств размера $n$ в множестве из $N$ элементов.
    - Справа: первый элемент из $N$ можно либо брать, либо не брать. Если мы не берём первый, то из $N-1$ остальных надо взять $n$. Если мы берём первый, то из $N-1$ остальных надо взять $n-1$.

* Число подмножеств размера $n$ в множестве из $N$ элементов:
\[
\sum_{r=0}^R C_R^r C_{N-R}^{n-r} = C_N^n, \text{ если } R \leq n \leq N-R
\]

    - Слева: представим себе, что из $N$ элементов $R$ окрашены заранее красным, а $N-R$ — белым. Если мы выбираем из большого множества $n$ элементов, то s$r$ из них будут окрашены красным, а $n-r$ — белым. Перебираем все возможные значения $r$.
    - Справа: количество подмножеств размера $n$ в множестве из $N$ элементов.




