---
title: "Дифференциальные формы вместо плотностей"
author: "Винни-Пух"
date: "`r Sys.Date()`"
lang: ru-RU
otherlangs: en-GB
fontsize: 11pt
biblio-style: alphabetic
mainfont: "Linux Libertine O"
sansfont: "Linux Libertine O"
monofont: "Linux Libertine O"
link-citations: yes
description: "Дифференциальные формы вместо плотностей"
output: 
  pdf_document:
    fig_caption: yes
    highlight: tango
    keep_tex: yes
    latex_engine: xelatex
    citation_package: biblatex
    number_sections: no
    toc: yes
header-includes: 
  - \newfontfamily{\cyrillicfonttt}{Linux Libertine O}
  - \newfontfamily{\cyrillicfont}{Linux Libertine O}
  - \newfontfamily{\cyrillicfontsf}{Linux Libertine O}
---

### Крамольная мысль

Рассказать второму курсу, как преобразовывать одномерные и совместные функции плотности с помощью дифференциальных форм. Это позволит рассмотреть гамма и бета распределения, например. 

Ни один определитель в ходе съёмок не пострадал :)

### Кратко про дифференциальные формы 

Неформальное определение. Дифференциальная форма — это объект, который приятно интегрировать. Обозначается так:

\[
f(x, y) \, dx \wedge dy
\]

Основное свойство дифференциальных форм:
\[
dx \wedge dy = - dy \wedge dx
\]

Из основного свойства немедленно следует, что
\[
dx \wedge dx = - dx \wedge dx = 0
\]

### Поехали!


Пример 1. Одномерная случайная величина

Вероятность попасть в отрезок $[x, x+dx]$ описывается формой с точностью до $o(dx)$:
\[
P(X \in [x; x+dx]) \sim \begin{cases}
2x dx; \text{ если } x\in [0;1] \\
0; \text{ иначе.}
\end{cases}
\]

* Найдите примерно $P(X \in [0.7, 0.71])$
* Найдите точно вероятность $P(X \in [0.7, 0.71])$
* Найдите дифференциальную форму для $Y=X^3$.
* Найдите функцию плотности $Y$

Примерно:

\[
P(X\in [0.7; 0.71]) \approx 2\cdot 0.7 \cdot 0.01 = 0.014
\]
Точно — через интеграл.

Выразим $X$ через $Y$, $X=Y^{1/3}$ и подставим $x$ в дифференциальную форму:
\[
2xdx = 2(y^{1/3})d(y^{1/3}) = \frac{2}{3}y^{-1/3}dy
\]

И полностью, с учётом границ:
\[
P(Y \in [y; y+dy]) \sim \begin{cases}
\frac{2}{3}y^{-1/3}dy, \text{ если } y \in [0;1] \\
0, \text{ иначе.}
\end{cases} 
\]

Функция плотности — это то, что стоит перед $dy$:

\[
f(y) = \begin{cases}
\frac{2}{3}y^{-1/3}, \text{ если } y \in [0;1] \\
0, \text{ иначе.}
\end{cases} 
\]


Пример 2. Переход к полярным координатам:

\[
\int \int f(x, y) \, dx \wedge dy 
\]

Хотим сделать замену $x = r \cos \phi$, $y = r\sin \phi$. Получаем, что
\begin{multline}
dx \wedge dy = (\cos \phi dr - r \sin \phi d\phi) \wedge (\sin \phi dr + r\cos \phi d\phi) = \\
=(\text{неважно}) \, dr \wedge dr + (r\cos^2\phi) \, dr \wedge d\phi + (-r\sin^2\phi) d\phi \wedge dr + (\text{неважно}) d\phi \wedge d\phi = \\
= (r\cos^2\phi) \, dr \wedge d\phi + (r\sin^2\phi) dr \wedge d\phi = r dr \wedge d\phi 
\end{multline}

Отсюда получаем правило перехода к полярным медведям:
\[
\int \int f(x, y) \, dx \wedge dy = \int \int f(r\cos\phi, r\sin \phi) r \, dr \wedge d \phi
\]


Пример 3. Время за которое студент Вовочка решит две задачи — это две независимых экспоненциально распределенных случайных величины с параметром $\lambda$: $X_1$, $X_2$. Рассмотрим новую пару величин: суммарное время решения двух задач, $S = X_1 + X_2$, и долю времени на первую задачу, $Y_1 = X_1 / S$.


* Найдите совместную плотность $Y_1$ и $S$;
* Являются ли $Y_1$ и $S$ независимыми?
* Найдите частные плотности $Y_1$ и $S$ с точностью до сомножителя

Поехали!

Выражаем $X_1$ и $X_2$ через новые переменные: $X_1 = Y_1 \cdot S$, $X_2 = (1 - Y_1) S$. Находим, что $dx_1 = sdy_1 + y_1 ds$, $dx_2 = (1-y_1)ds -sdy_1$. И отсюда 
\begin{multline}
dx_1 \wedge dx_2 = (sdy_1 + y_1 ds) \wedge ((1-y_1)ds -sdy_1) = \\
= s(1-y_1) \; dy_1 \wedge ds -y_1 s \; ds \wedge dy_1 + (\text{неважно}) \; ds\wedge ds + (\text{неважно}) \; dy_1 \wedge dy_1 = \\
= s(1-y_1) \; dy_1 \wedge ds + y_1 s \; dy_1 \wedge ds = s dy_1 \wedge ds
\end{multline}

Упрощаем дифференциальную форму в целом:
\[
f(x_1, x_2) dx_1 \wedge dx_2 = \lambda \exp(-\lambda x_1) \lambda \exp(-\lambda x_2) \, dx_1 \wedge dx_2 = \lambda^2 \exp( -\lambda s) s dy_1 \wedge ds
\]

Отсюда новая совместная плотность равна:

\[
f(y_1, s) = \begin{cases}
\lambda^2 \exp( -\lambda s) s, \text{ если } y_1 \in [0;1], s \geq 0 \\
0, \text{ иначе.}
\end{cases}
\]




Поскольку функция плотности распадается в произведение плотностей, можно сделать вывод, что величины $S = X_1 + X_2$ и $Y_1 = X_1/S$ независимы. Частные функции плотности с точностью до константы можно получить без интегрирования:

\[
f(y_1) \propto 1 \; \text{ если } y_1 \in [0;1] 
\]
Получается, что в данном случае константа пропорциональности равна 1, то есть
\[
f(y_1) = 1 \; \text{ если } y_1 \in [0;1] 
\]

И, следовательно,
\[
f(s) = \lambda^2 \exp( -\lambda s) s \; s \geq 0
\]


### Задачки для самостоятельного решения


#### Занудная задача

Совместная функция плотности величин $X$ и $Y$ имеет вид
\[
f(x, y) = \begin{cases}
4xy, \text{ если } x, y \in [0;1];\\
0, \text{ иначе }
\end{cases}
\]

* Выпишите дифференциальную форму вероятностей для пары $X$ и $Y$
* Найдите дифференциальную форму для $S = X+Y$ и $R = X/(X + Y)$.
* Найдите совместную функцию плотности для $S = X+Y$ и $R = X/(X + Y)$.

#### Преобразование Бокса-Мюллера

Величины $U_1$ и $U_2$ независимы и равномерны $U[0;1]$. Рассмотрим пару величин $Y_1 = R\cdot \cos \alpha$, $Y_2 = R\cdot \sin \alpha$, где $R=\sqrt{-2\ln U_1}$, а $\alpha = 2\pi U_2$.

* Выпишите дифференциальную форму для пары $U_1$, $U_2$
* Выпишите дифференциальную форму для пары $Y_1$, $Y_2$
* Найдите совместный закон распределения $Y_1$ и $Y_2$;
* Верно ли, что $Y_1$ и $Y_2$ независимы?
* Как распределены $Y_1$ и $Y_2$ по отдельности?

#### Вывод плотности бета-распределения

В Пуассоновском потоке с интенсивностью $\lambda$ время наступления $k$-го события распределено согласно гамма-распределению $Gamma(k, \lambda)$ и имеет вероятностную дифференциальную форму

\[
P(Y \in [y; y+dy]) = const \cdot y^{k-1} \cdot \exp(-\lambda y), \text{ при } y\geq 0;
\]

До прихода Ёжика Медвежонок сидел на крылечке один и насчитал $k_1$ падающую звезду. А после прихода Ёжика Медвежонок насчитал ещё $k_2$ падающих звёзд. Пусть $Y_1$ и $Y_2$ — время, которое которое наблюдал за звёздами Медвежонок до и после прихода Ёжика.

* Выпишите совместную дифференциальную форму для $Y_1$ и $Y_2$
* Найдите совместную дифференциальную форму для $S=Y_1 + Y_2$ и $Z=Y_1/S$.
* С точностью до сомножителя выпишите дифференциальную форму для доли времени, в течение которого Медвежонок наблюдал звёзды один. 
* Выпишите функцию плотности бета-распределения


### Источники мудрости

* Всё началось с одного ответа на форуме, [whuber, there's better way](https://stats.stackexchange.com/questions/36093)
* [David Bachman](https://arxiv.org/abs/math/0306194v1) Geometric approach to differential forms. Черновая версия опубликованной книжки.
* [Jonathan Gratus](https://arxiv.org/abs/1709.08492) A pictorial introduction to differential geometry. Ни одной формулы и только куча цветных картинок!
* [Lorenzo Sadun](https://arxiv.org/abs/1604.07862) Lecture Notes on Differential Forms. Приятные лекции.


